"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'ads3/static/js', 'serviceworker.js')

APP_NAME = 'Yorokobi'


#LOGIN_REDIRECT_URL = 'login_redirect'  # After login, go to this custom view

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q5r#5f=5w__f7&v#nd=bjyp(7xv0^9s#4b7gysjjd&ylm&)qz5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'ads3.MyUser'


# Application definition

INSTALLED_APPS = [
    
    
    'ads3',
    "django_extensions",
    'django.contrib.admin',
    'django.contrib.auth',
    'social_django',  
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # extensions
    'crispy_forms',
    'crispy_bootstrap5',
    'pwa',
    'webpush'
    
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    
]


#ASGI_APPLICATION = 'mysite.asgi.application'

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ads3.context_processors.settings',      # Add
                'social_django.context_processors.backends',  # <--
                'social_django.context_processors.login_redirect',
                #'ads.context_processors.app_name',
            ],
        },
    },
]


WSGI_APPLICATION = 'ecommerce.wsgi.application'

"""
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
        },
    },
}
"""

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

#STATIC_URL = 'static/'
STATIC_URL = 'static/'
#STATICFILES_DIRS = [BASE_DIR / "static"]  # Assuming your static folder is in the project root



#define the path where the imge and other media to store


MEDIA_URL = '/media/'
#this defin the absulte path to file system
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#CRISPY_TEMPLATE_PACK = 'bootstrap4'




# Configure the social login

try:
    from . import github_settings 
    SOCIAL_AUTH_GITHUB_KEY = github_settings.SOCIAL_AUTH_GITHUB_KEY
    SOCIAL_AUTH_GITHUB_SECRET = github_settings.SOCIAL_AUTH_GITHUB_SECRET
    print(github_settings.SOCIAL_AUTH_GITHUB_KEY, github_settings.SOCIAL_AUTH_GITHUB_SECRET)
except:
    print('When you want to use social login, please see dj4e-samples/github_settings-dist.py')

# https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#authentication-backends
# https://simpleisbetterthancomplex.com/tutorial/2016/10/24/how-to-add-social-login-to-django.html
AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    # 'social_core.backends.twitter.TwitterOAuth',
    # 'social_core.backends.facebook.FacebookOAuth2',

    'ads3.authentication.DriverBackend',
    'django.contrib.auth.backends.ModelBackend',
    
)




#user regestration conformation stuff

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'bearpinkie806@gmail.com'
EMAIL_HOST_PASSWORD = 'print("google.api");'
EMAIL_PORT = 587




PWA_APP_NAME = 'Saboady'
PWA_APP_DESCRIPTION = "Saboady PWA"
PWA_APP_THEME_COLOR = '#3f51b5'
PWA_APP_BACKGROUND_COLOR = '#3f51b5'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/ads3/list'
PWA_APP_STATUS_BAR_COLOR = '#3f51b5'
PWA_APP_ICONS = [
	{
		'src': '/static/images/S1.png',
		'sizes': '144x144'
	}
]
PWA_APP_ICONS_APPLE = [
	{
		'src': '/static/images/S1.png',
		'sizes': '144x144'
	}
]
PWA_APP_SPLASH_SCREEN = [
	{
	    'src': '/static/images/SabaodyLOGO.png',
            'sizes': '191x191'
	    #'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
	}
]
PWA_APP_SCREENSHOTS = [
    {
        "src": "/static/images/wide-screenshot.png",
        "sizes": "1920x1048",
        "type": "image/png",
        "form_factor": "wide"

    },
    {
        "src": "/static/images/phone-screenshot.png",
        "sizes": "520x886",
        "type": "image/png"
        

    }


]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'



#set the webpush public and privet vapid key

WEBPUSH_SETTINGS = {

    
    "VAPID_PUBLIC_KEY":"BO9VhfIdpJcQoOlt75zCigoAwMQIK4Atq58hTP98T0M9QcSkcHrTQB22HYp17XiD-SvI8mwuhgSQmigytW23egw",
    
    "VAPID_PRIVATE_KEY":"SAYjGhvt3I_7Hs3etZxdTrRHYykonCvHfRum67u-1rM",

    
    "VAPID_ADMIN_EMAIL": "viibug574@gmail.com"
}
