# Generated by Django 4.2.7 on 2024-07-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('auther', models.CharField(max_length=128)),
                ('puplisher', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
            ],
        ),
    ]
