# Generated by Django 4.2.7 on 2024-09-21 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads3', '0004_order_delivery_cost_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad3',
            name='price',
        ),
        migrations.CreateModel(
            name='ProductVaraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads3.ad3')),
            ],
        ),
    ]
