# Generated by Django 4.2.7 on 2024-09-21 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads3', '0006_ad3_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvaraint',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ads3.ad3'),
        ),
    ]
