# Generated by Django 4.2.7 on 2024-09-29 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads3', '0009_remove_orderitem_product_orderitem_product_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '3. Brands',
            },
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='ad3',
            options={'verbose_name_plural': '1. Products'},
        ),
        migrations.AlterModelOptions(
            name='tage',
            options={'verbose_name_plural': '2. Category'},
        ),
        migrations.RemoveField(
            model_name='ad3',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ad3',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='ad3',
            name='price',
        ),
        migrations.AddField(
            model_name='ad3',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad3',
            name='slug',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad3',
            name='specs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad3',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.AddField(
            model_name='ad3',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads3.brand'),
        ),
    ]
