# Generated by Django 4.2.7 on 2024-10-11 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads3', '0013_alter_driverorder_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsciptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_secret', models.TextField()),
                ('key', models.TextField()),
                ('endpoint', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
