# Generated by Django 4.2.7 on 2024-10-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads3', '0014_subsciptiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsciption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_secret', models.TextField()),
                ('key', models.TextField()),
                ('endpoint', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='SubsciptionDetail',
        ),
    ]
