# Generated by Django 4.2.7 on 2024-10-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads3', '0015_subsciption_delete_subsciptiondetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsciption',
            new_name='Subscription',
        ),
    ]
