# Generated by Django 4.2.7 on 2024-08-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many', '0002_course_person_membership_course_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='courses',
            field=models.ManyToManyField(through='many.membership', to='many.course'),
        ),
    ]
